#' Extract Sample Names from Cell Ranger Output Directories
#'
#' Scans a specified parent directory for 10x Genomics Cell Ranger output folders
#' and extracts clean sample names. It automatically formats the names by stripping
#' standard Cell Ranger suffixes (such as \code{"_filtered_feature_bc_matrix"} or
#' \code{"_feature_bc_matrix"}) from the sub-directory folder names.
#'
#' @param filtered_dir Character. The file path to the parent directory containing the individual sample output folders.
#'
#' @return A character vector of cleaned sample names, derived from the sub-directory names.
#'
#' @export
#'
#' @examples
#' \dontrun{
#' # Assuming you have a directory "data/cellranger_outputs" containing folders like:
#' # "Patient1_filtered_feature_bc_matrix" and "Patient2_filtered_feature_bc_matrix"
#'
#' my_samples <- get_sample_names(filtered_dir = "data/cellranger_outputs")
#'
#' print(my_samples)
#' # [1] "Patient1" "Patient2"
#' }
get_sample_names <- function(filtered_dir) {
  dirs <- list.dirs(path = filtered_dir, recursive = FALSE, full.names = FALSE)
  sample_names <- sapply(dirs, function(x) gsub("(_filtered)?_feature_bc_matrix", "", x))
  return(sample_names)
}

#--------------------------------------------------

#' Load Filtered and Raw 10x Genomics Count Matrices
#'
#' Batch loads 10x Genomics formatted sparse matrices (matrix, features, and barcodes)
#' for multiple samples. It simultaneously reads both the 'filtered' (cell-containing)
#' and 'raw' (all droplets) outputs from Cell Ranger using Seurat's \code{ReadMtx}.
#' Loading both matrices is highly useful for downstream ambient RNA decontamination
#' workflows (such as SoupX) that require the empty droplet background to estimate
#' the ambient RNA profile. Includes a progress bar to track loading status.
#'
#' @param sample_names Character vector. A list of sample identifiers corresponding to the folder prefixes (e.g., as generated by \code{get_sample_names()}).
#' @param filtered_dir Character. The parent directory path containing the \code{"*_filtered_feature_bc_matrix"} folders.
#' @param raw_dir Character. The parent directory path containing the \code{"*_raw_feature_bc_matrix"} folders.
#'
#' @return A named list containing two top-level elements:
#' \itemize{
#'   \item \code{filtered}: A named list of the filtered sparse count matrices (\code{dgCMatrix}) for each sample.
#'   \item \code{raw}: A named list of the raw sparse count matrices (\code{dgCMatrix}) for each sample.
#' }
#'
#' @export
#'
#' @examples
#' \dontrun{
#' # 1. Extract sample names using your helper function
#' my_samples <- get_sample_names(filtered_dir = "data/filtered_outputs")
#'
#' # 2. Load both raw and filtered matrices for all samples
#' counts_list <- load_counts(
#'   sample_names = my_samples,
#'   filtered_dir = "data/filtered_outputs",
#'   raw_dir = "data/raw_outputs"
#' )
#'
#' # 3. Access the matrices for the first sample to pass into SoupX
#' patient1_filt <- counts_list$filtered[["Patient1"]]
#' patient1_raw  <- counts_list$raw[["Patient1"]]
#'
#' # Check dimensions
#' dim(patient1_filt)
#' dim(patient1_raw)
#' }
load_counts <- function(sample_names, filtered_dir, raw_dir) {
  cts_filtered_list <- list()
  cts_raw_list <- list()

  cat("Loading counts:\n")
  pb <- txtProgressBar(min = 0, max = length(sample_names), style = 3)

  for (i in seq_along(sample_names)) {
    sample_name <- sample_names[i]
    filtered_path <- file.path(filtered_dir, paste0(sample_name, "_filtered_feature_bc_matrix"))
    raw_path <- file.path(raw_dir, paste0(sample_name, "_raw_feature_bc_matrix"))

    cts_filtered <- ReadMtx(
      mtx = paste0(filtered_path, '/matrix.mtx.gz'),
      features = paste0(filtered_path, "/features.tsv.gz"),
      cells = paste0(filtered_path, "/barcodes.tsv.gz")
    )

    cts_raw <- ReadMtx(
      mtx = paste0(raw_path, '/matrix.mtx.gz'),
      features = paste0(raw_path, "/features.tsv.gz"),
      cells = paste0(raw_path, "/barcodes.tsv.gz")
    )

    cts_filtered_list[[sample_name]] <- cts_filtered
    cts_raw_list[[sample_name]] <- cts_raw

    setTxtProgressBar(pb, i)
  }
  close(pb)
  return(list(filtered = cts_filtered_list, raw = cts_raw_list))
}

# ---------------------------------------------------------

#' Create SoupChannel Objects for Ambient RNA Decontamination
#'
#' Batch initializes \code{SoupChannel} objects for multiple samples using lists of
#' raw (unfiltered) and filtered count matrices. This is a required preparation step
#' for the \code{SoupX} pipeline, which uses the empty droplets in the raw matrix
#' ("Table of Drops" or \code{tod}) to estimate the ambient RNA profile contaminating
#' the true cells in the filtered matrix ("Table of Cells" or \code{toc}).
#'
#' @param cts_raw_list A named list of raw sparse count matrices (containing all droplets), typically from the \code{raw} element of \code{load_counts()}.
#' @param cts_filtered_list A named list of filtered sparse count matrices (containing only called cells), typically from the \code{filtered} element of \code{load_counts()}.
#' @param sample_names Character vector. A list of sample identifiers used as keys to match the matrices in both lists and name the output list elements.
#'
#' @return A named list of \code{SoupChannel} objects, ready for downstream contamination fraction estimation and expression adjustment.
#'
#' @export
#'
#' @examples
#' \dontrun{
#' # Assuming you have loaded matrices using the previous pipeline function
#' counts_list <- load_counts(
#'   sample_names = my_samples,
#'   filtered_dir = "data/filtered_outputs",
#'   raw_dir = "data/raw_outputs"
#' )
#'
#' # Initialize the SoupChannels
#' soup_channels <- create_soup_channels(
#'   cts_raw_list = counts_list$raw,
#'   cts_filtered_list = counts_list$filtered,
#'   sample_names = my_samples
#' )
#'
#' # The result is a list ready for autoEstCont() and adjustCounts()
#' print(soup_channels[["Patient1"]])
#' }
create_soup_channels <- function(cts_raw_list, cts_filtered_list, sample_names) {
  soup_list <- list()
  cat("Creating SoupChannel objects:\n")
  pb <- txtProgressBar(min = 0, max = length(sample_names), style = 3)

  for (i in seq_along(sample_names)) {
    sample_name <- sample_names[i]
    sc <- SoupChannel(tod = cts_raw_list[[sample_name]], toc = cts_filtered_list[[sample_name]])
    soup_list[[sample_name]] <- sc
    setTxtProgressBar(pb, i)
  }
  close(pb)
  return(soup_list)
}


#---------------------------------------------------------

#' Generate Initial Seurat Clustering for SoupX Estimation
#'
#' Batch processes a list of filtered count matrices through a rapid, standard Seurat
#' pipeline (LogNormalization, Variable Feature selection, Scaling, PCA, Neighborhood
#' Graph construction, Clustering, and UMAP). The primary purpose of this function is
#' to quickly generate the high-resolution clusters (defaulting to \code{resolution = 1.8})
#' required by SoupX. Over-clustering at this stage is highly recommended for accurate
#' ambient RNA profiling via \code{SoupX::autoEstCont()}.
#'
#' @param cts_filtered_list A named list of filtered sparse count matrices, typically generated by the \code{filtered} element of \code{load_counts()}.
#' @param sample_names Character vector. A list of sample identifiers used as keys to match the matrices in the list and assign project names to the Seurat objects.
#'
#' @return A named list of processed \code{Seurat} objects. Each object contains a standard PCA, UMAP embedding, and high-resolution cluster identities stored in the active \code{Idents}.
#'
#' @export
#'
#' @examples
#' \dontrun{
#' # Assuming you have already loaded your filtered matrices
#' counts_list <- load_counts(my_samples, "data/filtered", "data/raw")
#'
#' # Quickly cluster all samples to prepare them for SoupX
#' initial_seurat_list <- create_seurat_for_clustering(
#'   cts_filtered_list = counts_list$filtered,
#'   sample_names = my_samples
#' )
#'
#' # The clusters from these objects can now be extracted and fed into SoupChannels
#' # e.g., soup_channels[[1]] <- setClusters(soup_channels[[1]],
#' # initial_seurat_list[[1]]$seurat_clusters)
#' }
create_seurat_for_clustering <- function(cts_filtered_list, sample_names) {
  seurat_list <- list()
  cat("Clustering for SoupX (Seurat pipeline):\n")
  pb <- txtProgressBar(min = 0, max = length(sample_names), style = 3)

  for (i in seq_along(sample_names)) {
    sample_name <- sample_names[i]
    seurat_temp <- CreateSeuratObject(counts = cts_filtered_list[[sample_name]], project = sample_name)
    seurat_temp <- NormalizeData(seurat_temp)
    seurat_temp <- FindVariableFeatures(seurat_temp)
    seurat_temp <- ScaleData(seurat_temp)
    # seurat_temp <- SCTransform(seurat_temp)
    seurat_temp <- RunPCA(seurat_temp, verbose = FALSE)
    seurat_temp <- FindNeighbors(seurat_temp, dims = 1:50)
    seurat_temp <- FindClusters(seurat_temp, resolution = 1.8)
    seurat_temp <- RunUMAP(seurat_temp, dims = 1:50)

    seurat_list[[sample_name]] <- seurat_temp
    setTxtProgressBar(pb, i)
  }
  close(pb)
  return(seurat_list)
}

# -----------------------------------------------------

#' Estimate and Remove Ambient RNA Contamination
#'
#' Integrates \code{SoupChannel} objects with initial high-resolution clustering
#' to automatically estimate the ambient RNA contamination fraction (\code{rho})
#' via \code{SoupX::autoEstCont()}. Includes a robust manual override system
#' allowing you to artificially increase the estimated contamination fraction
#' (e.g., adding 5% extra background removal) either globally across all samples
#' or selectively for specific noisy samples. Finally, it applies the chosen
#' correction method to remove the background noise and returns the cleaned count matrices.
#'
#' @param soup_list A named list of \code{SoupChannel} objects, typically generated by \code{create_soup_channels()}.
#' @param seurat_list A named list of clustered \code{Seurat} objects, typically generated by \code{create_seurat_for_clustering()}. Used solely to supply high-resolution cluster identities back to the SoupChannels.
#' @param cts_filtered_list A named list of filtered sparse count matrices. Used to extract the exact cell barcodes to ensure 1:1 mapping with the clusters.
#' @param sample_names Character vector. A list of sample identifiers corresponding to the names in the input lists.
#' @param mulFac Numeric. A percentage to artificially add to the auto-estimated contamination fraction (e.g., \code{mulFac = 5} adds \code{0.05} to the \code{rho} value). Default is 0.
#' @param manual_contam Character vector. A list of specific sample names to apply the \code{mulFac} adjustment to. Only evaluated if \code{manual = TRUE}. Default is an empty list.
#' @param manual Logical. Controls the application of \code{mulFac}. If \code{FALSE}, \code{mulFac} is applied globally to ALL samples. If \code{TRUE}, \code{mulFac} is applied ONLY to the specific samples listed in \code{manual_contam}. Default is FALSE.
#' @param methods Character. The method to use for count adjustment passed to \code{SoupX::adjustCounts()}. Options include "subtraction", "soupOnly", or "multinomial". Default is "subtraction".
#' @param pCut Numeric. The p-value threshold used for identifying cells expressing genes above background levels when \code{methods = "soupOnly"}. Default is 0.01.
#'
#' @return A named list containing two elements:
#' \itemize{
#'   \item \code{soup_list_all}: A list of the updated \code{SoupChannel} objects with their final \code{rho} values calculated and set.
#'   \item \code{corrected_list}: A list of the final, decontaminated sparse count matrices (rounded to integers), ready to be used to create your final Seurat objects.
#' }
#'
#' @export
#'
#' @examples
#' \dontrun{
#' # Assuming soup_channels and seurat_clusters were generated previously
#'
#' # Example 1: Run standard auto-estimation with no manual overrides
#' clean_data <- estimate_contamination(
#'   soup_list = soup_channels,
#'   seurat_list = initial_seurat_objs,
#'   cts_filtered_list = counts_list$filtered,
#'   sample_names = my_samples,
#'   methods = "subtraction"
#' )
#'
#' # Example 2: Sample "Patient_3" looks particularly noisy.
#' # Add an extra 5% (0.05) to its estimated contamination fraction.
#' clean_data_adjusted <- estimate_contamination(
#'   soup_list = soup_channels,
#'   seurat_list = initial_seurat_objs,
#'   cts_filtered_list = counts_list$filtered,
#'   sample_names = my_samples,
#'   mulFac = 5,
#'   manual = TRUE,
#'   manual_contam = c("Patient_3")
#' )
#'
#' # Extract the cleaned matrix for downstream processing
#' p3_clean_matrix <- clean_data_adjusted$corrected_list[["Patient_3"]]
#' }
estimate_contamination <- function(
    soup_list,
    seurat_list,
    cts_filtered_list,
    sample_names,
    mulFac = 0,
    manual_contam = list(),     # character vector of sample names to override
    manual = FALSE,             # if TRUE, apply mulFac to all
    methods = "subtraction",
    pCut = 0.01
) {
  soup_list_all <- list()
  corrected_list <- list()

  cat("Estimating contamination:\n")
  pb <- txtProgressBar(min = 0, max = length(sample_names), style = 3)

  for (i in seq_along(sample_names)) {
    sample_name <- sample_names[i]
    sc <- soup_list[[sample_name]]
    seurat_temp <- seurat_list[[sample_name]]

    # Assign clusters
    clusters <- seurat_temp$seurat_clusters
    names(clusters) <- colnames(cts_filtered_list[[sample_name]])
    sc <- setClusters(sc, clusters)

    # Auto estimate contamination
    sc <- autoEstCont(sc)

    # Extract estimated rho
    estimated_rho <- unique(sc$metaData$rho)
    if (length(estimated_rho) != 1) {
      stop("Sample ", sample_name, ": Expected a single rho value but got: ", paste(estimated_rho, collapse = ", "))
    }
    estimated_rho <- as.numeric(estimated_rho)

    # Determine final contamination fraction
    if (!manual) {
      confrac <- estimated_rho + (mulFac / 100)
      message("Sample: ", sample_name, " | MANUAL mode active | Adjusted rho: ", round(confrac, 4))
    } else {
      if (sample_name %in% manual_contam) {
        confrac <- estimated_rho + (mulFac / 100)
        message("Sample: ", sample_name, " | SELECTIVE manual override | Adjusted rho: ", round(confrac, 4))
      } else {
        confrac <- estimated_rho
        message("Sample: ", sample_name, " | Auto-estimated rho: ", round(confrac, 4))
      }
    }

    # Apply contamination fraction
    sc <- setContaminationFraction(sc, confrac)
    soup_list_all[[sample_name]] <- sc

    # Announce method used
    msg <- paste0("Sample: ", sample_name, " | Adjusting counts using method = '", methods, "'")
    if (methods == "soupOnly") {
      msg <- paste0(msg, " (with pCut = ", pCut, ")")
    }
    message(msg)

    # Adjust counts
    corrected <- adjustCounts(sc, method = methods, pCut = pCut, roundToInt = TRUE)
    corrected_list[[sample_name]] <- corrected

    setTxtProgressBar(pb, i)
  }

  close(pb)

  return(list(
    soup_list_all = soup_list_all,
    corrected_list = corrected_list
  ))
}

# --------------------------------------------------------

#' Initialize Final Seurat Objects from Decontaminated Counts
#'
#' Takes a list of fully processed \code{SoupChannel} objects (where the contamination
#' fraction has already been estimated and set), extracts the background-corrected count
#' matrices, and initializes fresh \code{Seurat} objects. During initialization, it applies
#' standard baseline filtering (\code{min.cells = 3}, \code{min.features = 200}) and
#' automatically calculates the mitochondrial read percentage (\code{mitoPercent}) for
#' immediate use in downstream quality control.
#'
#' @param soup_list_all A named list of \code{SoupChannel} objects that have their contamination fraction (\code{rho}) set. Typically the \code{soup_list_all} element returned by \code{estimate_contamination()}.
#' @param sample_names Character vector. A list of sample identifiers used to match the list elements and assign the \code{project} name to each Seurat object.
#'
#' @return A named list of initialized \code{Seurat} objects containing the decontaminated count matrices and a newly appended \code{mitoPercent} metadata column.
#'
#' @export
#'
#' @examples
#' \dontrun{
#' # Assuming clean_data is the list returned by estimate_contamination()
#'
#' final_seurat_list <- create_final_seurat(
#'   soup_list_all = clean_data$soup_list_all,
#'   sample_names = my_samples
#' )
#'
#' # The objects are now ready for standard Seurat QC filtering!
#' patient1_seurat <- final_seurat_list[["Patient_1"]]
#' head(patient1_seurat@meta.data)
#' }
create_final_seurat <- function(soup_list_all, sample_names) {
  final_seurat_list <- list()
  cat("Creating final Seurat objects with corrected counts:\n")
  pb <- txtProgressBar(min = 0, max = length(sample_names), style = 3)

  for (i in seq_along(sample_names)) {
    sample_name <- sample_names[i]
    sc <- soup_list_all[[sample_name]]
    corrected_counts <- adjustCounts(sc, roundToInt = TRUE)

    seurat_ind <- CreateSeuratObject(counts = corrected_counts, project = sample_name, min.cells = 3, min.features = 200)
    seurat_ind$mitoPercent <- PercentageFeatureSet(seurat_ind, pattern = "^MT-")

    final_seurat_list[[sample_name]] <- seurat_ind
    setTxtProgressBar(pb, i)
  }
  close(pb)
  return(final_seurat_list)
}


# --------------------------------------------------------

#' Run End-to-End Preparation Pipeline for SoupX Decontamination
#'
#' Acts as a master wrapper to execute the entire data loading and preparation phase
#' for ambient RNA removal. It automatically extracts sample names from the directory
#' structure, loads both raw and filtered Cell Ranger matrices, initializes the
#' \code{SoupChannel} objects, and runs a rapid Seurat clustering pipeline. The output
#' is a comprehensive bundled list containing all the necessary objects to feed directly
#' into the final contamination estimation and correction steps.
#'
#' @param filtered_dir Character. The file path to the parent directory containing the Cell Ranger \code{"*_filtered_feature_bc_matrix"} folders.
#' @param raw_dir Character. The file path to the parent directory containing the Cell Ranger \code{"*_raw_feature_bc_matrix"} folders.
#' @param manual_contam Character vector. An optional list of specific sample names that will later require a manual contamination override (e.g., adding an artificial penalty to the estimated rho). Default is \code{NULL} (which evaluates to an empty list).
#'
#' @return A structured, named list containing five top-level elements:
#' \itemize{
#'   \item \code{sample_names}: A character vector of the extracted sample identifiers.
#'   \item \code{counts_lists}: A list containing both \code{raw} and \code{filtered} sparse count matrices.
#'   \item \code{soup_list}: A list of initialized \code{SoupChannel} objects.
#'   \item \code{seurat_for_clustering}: A list of processed \code{Seurat} objects with high-resolution clusters stored in their active identities.
#'   \item \code{manual_contam}: The forwarded list of samples designated for manual overrides.
#' }
#'
#' @export
#'
#' @examples
#' \dontrun{
#' # Run the entire preparation pipeline in one line
#' soupx_prep_data <- prepare_soupx_inputs(
#'   filtered_dir = "data/cellranger/filtered",
#'   raw_dir = "data/cellranger/raw",
#'   manual_contam = c("Patient_3") # Flag this patient for manual adjustment later
#' )
#'
#' # Feed the bundled output directly into your estimation function
#' clean_data <- estimate_contamination(
#'   soup_list = soupx_prep_data$soup_list,
#'   seurat_list = soupx_prep_data$seurat_for_clustering,
#'   cts_filtered_list = soupx_prep_data$counts_lists$filtered,
#'   sample_names = soupx_prep_data$sample_names,
#'   manual_contam = soupx_prep_data$manual_contam,
#'   mulFac = 5,
#'   manual = TRUE
#' )
#' }
prepare_soupx_inputs <- function(filtered_dir, raw_dir, manual_contam = NULL) {
  sample_names <- get_sample_names(filtered_dir)

  counts_lists <- load_counts(sample_names, filtered_dir, raw_dir)

  soup_list <- create_soup_channels(counts_lists$raw, counts_lists$filtered, sample_names)

  seurat_for_clustering <- create_seurat_for_clustering(counts_lists$filtered, sample_names)

  # If manual_contam is NULL, default to empty list
  if (is.null(manual_contam)) {
    manual_contam <- list()
  }

  return(list(
    sample_names = sample_names,
    counts_lists = counts_lists,
    soup_list = soup_list,
    seurat_for_clustering = seurat_for_clustering,
    manual_contam = manual_contam
  ))
}


# ----------------------------------------------------------

#' Execute Final SoupX Contamination Removal and Seurat Initialization
#'
#' The second half of the master ambient RNA removal workflow. It takes the bundled
#' preparation data (generated by \code{prepare_soupx_inputs}), estimates the
#' contamination fractions using the high-resolution clusters, applies any specified
#' manual overrides, and adjusts the count matrices. Finally, it automatically
#' initializes a fresh list of \code{Seurat} objects using the decontaminated counts,
#' returning a comprehensive list of all objects generated during the process.
#'
#' @param prep_output A structured list containing \code{sample_names}, \code{soup_list}, \code{seurat_for_clustering}, and \code{counts_lists}. Typically the direct output of \code{prepare_soupx_inputs()}.
#' @param multiFac Numeric. A percentage to artificially add to the auto-estimated contamination fraction (\code{rho}). Default is 0.
#' @param manual_contam Character vector. An optional list of specific sample names to selectively apply the \code{multiFac} adjustment to. Default is an empty list.
#' @param pCut Numeric. The p-value threshold used for identifying cells expressing genes above background levels when \code{methods = "soupOnly"}. Default is 0.01.
#' @param methods Character. The method to use for count adjustment passed to \code{SoupX::adjustCounts()}. Options include "subtraction", "soupOnly", or "multinomial". Default is "subtraction".
#'
#' @return A structured, named list containing three top-level elements:
#' \itemize{
#'   \item \code{final_seurat}: A list of the final, initialized \code{Seurat} objects containing the background-corrected counts and baseline metadata (e.g., \code{mitoPercent}).
#'   \item \code{soup_objects}: A list of the updated \code{SoupChannel} objects with their calculated \code{rho} values.
#'   \item \code{seurat_clustering}: A list of the preliminary \code{Seurat} objects used to generate the high-resolution clusters for estimation.
#' }
#'
#' @export
#'
#' @examples
#' \dontrun{
#' # 1. Run the preparation phase
#' soupx_prep_data <- prepare_soupx_inputs(
#'   filtered_dir = "data/cellranger/filtered",
#'   raw_dir = "data/cellranger/raw"
#' )
#'
#' # 2. Execute the contamination removal and generate final Seurat objects
#' final_pipeline_output <- run_soupx_post_clustering(
#'   prep_output = soupx_prep_data,
#'   multiFac = 2,                 # Add 2% extra contamination penalty
#'   manual_contam = c("Donor_A"), # Only apply the penalty to Donor_A
#'   methods = "subtraction"
#' )
#'
#' # 3. Extract your final cleaned Seurat objects for downstream integration
#' my_clean_seurats <- final_pipeline_output$final_seurat
#' }
run_soupx_post_clustering <- function(
    prep_output,
    multiFac = 0,
    manual_contam = list(),
    pCut = 0.01,
    methods = "subtraction"       # optional: force ambient gene correction
) {
  sample_names <- prep_output$sample_names
  soup_list <- prep_output$soup_list
  seurat_for_clustering <- prep_output$seurat_for_clustering
  counts_filtered <- prep_output$counts_lists$filtered

  contamination_result <- estimate_contamination(
    soup_list = soup_list,
    seurat_list = seurat_for_clustering,
    cts_filtered_list = counts_filtered,
    sample_names = sample_names,
    mulFac = multiFac,
    manual_contam = manual_contam,
    methods = methods,
    pCut = pCut
  )

  final_seurat_list <- create_final_seurat(
    soup_list_all = contamination_result$soup_list_all,
    sample_names = sample_names
  )

  return(list(
    final_seurat = final_seurat_list,
    soup_objects = contamination_result$soup_list_all,
    seurat_clustering = seurat_for_clustering
  ))
}

# ---------------------------------------------------------------

#' Execute the Complete One-Step SoupX Decontamination Pipeline
#'
#' A unified master wrapper that executes the entire ambient RNA removal workflow
#' in a single command. It automatically extracts sample names from the directory
#' structure, loads the raw and filtered Cell Ranger matrices, initializes \code{SoupChannel}
#' objects, runs a quick clustering pipeline to define groups, estimates and removes
#' ambient RNA contamination, and immediately wraps the cleaned count matrices into
#' a list of fresh \code{Seurat} objects ready for downstream quality control.
#'
#' @param filtered_dir Character. The file path to the parent directory containing the Cell Ranger \code{"*_filtered_feature_bc_matrix"} folders.
#' @param raw_dir Character. The file path to the parent directory containing the Cell Ranger \code{"*_raw_feature_bc_matrix"} folders.
#' @param multiFac Numeric. A percentage to artificially add to the auto-estimated contamination fraction (\code{rho}) across all samples (e.g., passing 5 adds 0.05 to the estimated rho). Default is 0.
#'
#' @return A structured, named list containing three top-level elements:
#' \itemize{
#'   \item \code{final_seurat}: A list of the final, initialized \code{Seurat} objects containing the background-corrected counts and baseline metadata.
#'   \item \code{soup_objects}: The output list from the contamination estimation step, containing the updated \code{SoupChannel} objects and corrected matrices.
#'   \item \code{seurat_clustering}: A list of the preliminary \code{Seurat} objects used to generate the high-resolution clusters for ambient RNA estimation.
#' }
#'
#' @export
#'
#' @examples
#' \dontrun{
#' # Run the entire start-to-finish pipeline in a single line
#' final_pipeline_output <- process_soupx_samples(
#'   filtered_dir = "data/cellranger/filtered",
#'   raw_dir = "data/cellranger/raw",
#'   multiFac = 2 # Globally add a 2% contamination penalty to all samples
#' )
#'
#' # Extract your final cleaned Seurat objects for downstream integration
#' my_clean_seurats <- final_pipeline_output$final_seurat
#' }
process_soupx_samples <- function(filtered_dir, raw_dir, multiFac=0) {
  sample_names <- get_sample_names(filtered_dir)

  counts_lists <- load_counts(sample_names, filtered_dir, raw_dir)

  soup_list <- create_soup_channels(counts_lists$raw, counts_lists$filtered, sample_names)

  seurat_for_clustering <- create_seurat_for_clustering(counts_lists$filtered, sample_names)

  soup_list_all <- estimate_contamination(soup_list, seurat_for_clustering, counts_lists$filtered, sample_names, multiFac)

  final_seurat_list <- create_final_seurat(soup_list_all, sample_names)

  return(list(final_seurat = final_seurat_list,
              soup_objects = soup_list_all,
              seurat_clustering = seurat_for_clustering))
}

# --------------------------------------------------------------

#' Update Seurat Object with SoupX-Corrected Counts and Metadata
#'
#' Merges a list of SoupX-processed Seurat objects and seamlessly maps their
#' background-corrected count matrices and updated QC metrics back onto a pre-existing
#' Seurat object. It handles the tedious formatting steps, such as barcode stripping,
#' standardizing mitochondrial column names, and intersecting cells/genes to prevent
#' dimension mismatches. Finally, it replaces the raw counts layer in the original
#' object with the decontaminated data.
#'
#' @param original_seurat A pre-existing \code{Seurat} object that you wish to update with the cleaned counts.
#' @param soupx_seurat_list A named list of \code{Seurat} objects containing SoupX-corrected counts, typically the output of \code{create_final_seurat()}.
#' @param mito_colname Character. The name of the mitochondrial percentage column in the SoupX objects. It will be automatically standardized to \code{"pct_counts_mt"} during the transfer. Default is \code{"mitoPercent"}.
#' @param counts_assay Character. The name of the assay in the original object where the counts layer should be updated. Default is \code{"RNA"}.
#' @param rename_barcodes Logical. If \code{TRUE}, strips the common \code{"-1"} suffix from the barcodes in the merged SoupX object to ensure they match standard Seurat formatting. Default is \code{TRUE}.
#' @param save_path Character. An optional file path (.rds) to automatically save the updated Seurat object to disk. Default is \code{NULL} (does not save).
#'
#' @return An updated \code{Seurat} object containing the decontaminated count matrix and matching QC metadata (\code{nCount_RNA}, \code{nFeature_RNA}, \code{pct_counts_mt}). The object is strictly subsetted to contain only the overlapping valid cells and genes.
#'
#' @export
#'
#' @examples
#' \dontrun{
#' # Assuming 'my_seurat' is an existing object you want to clean,
#' # and 'pipeline_out' is the list returned by process_soupx_samples()
#'
#' cleaned_seurat <- addSoupXMetaToSeurat(
#'   original_seurat = my_seurat,
#'   soupx_seurat_list = pipeline_out$final_seurat,
#'   mito_colname = "mitoPercent",
#'   counts_assay = "RNA",
#'   rename_barcodes = TRUE,
#'   save_path = "Results/Seurat_SoupX_Cleaned.rds"
#' )
#'
#' # The 'cleaned_seurat' object now contains the background-corrected counts
#' # in its RNA assay, ready for standard downstream normalization!
#' }
addSoupXMetaToSeurat <- function(original_seurat,
                                 soupx_seurat_list,
                                 mito_colname = "mitoPercent",
                                 counts_assay = "RNA",
                                 rename_barcodes = TRUE,
                                 save_path = NULL) {
  library(Seurat)

  message("Merging SoupX Seurat objects...")
  merged_seurat <- merge(
    soupx_seurat_list[[1]],
    y = soupx_seurat_list[-1],
    add.cell.ids = names(soupx_seurat_list),
    project = "MergedSoupX"
  )

  if (rename_barcodes) {
    message("Renaming barcodes (removing '-1')...")
    old_barcodes <- colnames(merged_seurat)
    new_barcodes <- gsub("-1$", "", old_barcodes)
    colnames(merged_seurat) <- new_barcodes
  }

  # Standardize mito column name
  if (mito_colname %in% colnames(merged_seurat@meta.data)) {
    colnames(merged_seurat@meta.data)[colnames(merged_seurat@meta.data) == mito_colname] <- "pct_counts_mt"
  }

  message("Transferring metadata (nCount_RNA, nFeature_RNA, pct_counts_mt)...")
  required_cols <- c("nCount_RNA", "nFeature_RNA", "pct_counts_mt")
  missing_cols <- setdiff(required_cols, colnames(merged_seurat@meta.data))
  if (length(missing_cols) > 0) {
    stop("Missing columns in SoupX metadata: ", paste(missing_cols, collapse = ", "))
  }

  # Match metadata by shared barcodes
  matched_cells <- intersect(colnames(original_seurat), rownames(merged_seurat@meta.data))
  if (length(matched_cells) == 0) {
    stop("No overlapping cell barcodes found between original and merged Seurat objects.")
  }

  matched_meta <- merged_seurat@meta.data[matched_cells, required_cols, drop = FALSE]
  updated_seurat <- AddMetaData(original_seurat, metadata = matched_meta)

  message("Joining RNA assay layers in merged object...")
  merged_seurat[[counts_assay]] <- JoinLayers(merged_seurat[[counts_assay]])

  message("Preparing raw count transfer...")
  cells_to_use <- colnames(original_seurat)
  genes_to_use <- rownames(original_seurat[[counts_assay]])

  missing_cells <- setdiff(cells_to_use, colnames(merged_seurat))
  missing_genes <- setdiff(genes_to_use, rownames(merged_seurat[[counts_assay]]))
  if (length(missing_cells) > 0) {
    message(" Warning: Some cells not found in merged object. Subsetting...")
  }

  if (length(missing_genes) > 0) {
    message(" Warning: Some genes not found in merged object. Subsetting...")
  }

  # Subset to only available ones (preserve order)
  valid_cells <- intersect(cells_to_use, colnames(merged_seurat))
  valid_genes <- intersect(genes_to_use, rownames(merged_seurat[[counts_assay]]))

  raw_counts <- GetAssayData(merged_seurat, assay = counts_assay, layer = "counts")[valid_genes, valid_cells, drop = FALSE]

  # Subset the original object to match valid dimensions (if necessary)
  updated_seurat <- subset(updated_seurat, cells = valid_cells, features = valid_genes)

  # Set counts
  updated_seurat[[counts_assay]] <- SetAssayData(
    updated_seurat[[counts_assay]],
    layer = "counts",
    new.data = raw_counts
  )

  if (!is.null(save_path)) {
    message("Saving updated Seurat object to: ", save_path)
    saveRDS(updated_seurat, file = save_path)
  }

  message("Done: Metadata and counts transferred successfully.")
  return(updated_seurat)
}
